---
  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes # Run the equivalent of "apt-get update" before the operation.
    vars:
      packages:
        - kubelet
        - kubeadm 
        - kubectl

  # - name: Configure node ip
  #   lineinfile:
  #     path: /etc/default/kubelet
  #     line: KUBELET_EXTRA_ARGS=--node-ip={{ --node-name }}

  - name: Directory exists - /var/lib/kubelet
    ansible.builtin.file:
      path: "/var/lib/kubelet"
      state: directory

  - name: File exists - Set Systemd as Cgroups for Kubelet
    ansible.builtin.file:
      path: "/var/lib/kubelet/config.yaml"
      state: touch

  - name: Set Systemd as Cgroups for Kubelet
    ansible.builtin.blockinfile:
      path: "/var/lib/kubelet/config.yaml"
      block: | 
            kind: KubeletConfiguration 
            apiVersion: kubelet.config.k8s.io/v1beta1 
            cgroupDriver: systemd
    # notify:
    #   - containerd status
    #   - kubelet status
  
  - name: containerd status
    service: 
      name: containerd
      state: restarted

  - name: kubelet status
    service: 
      name: kubelet
      state: restarted