---
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - python3-apt
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - lsb-release

  # - name: File exists - Forwarding IPv4 and letting iptables see bridged traffic
  #   ansible.builtin.file:
  #     path: "/etc/modules-load.d/k8s.conf"
  #     state: touch

  - name: Copy Content - Forwarding IPv4 and letting iptables see bridged traffic
    ansible.builtin.blockinfile:
      path: "/etc/sysctl.d/k8s.conf"
      block: |
            overlay 
            br_netfilter

  - name: modprobe
    shell: |
          sudo modprobe overlay
          sudo modprobe br_netfilter

  - name: sysctl required params - Forwarding IPv4 and letting iptables see bridged traffic
    ansible.builtin.blockinfile:
      path: "/etc/modules-load.d/k8s.conf"
      block: | 
            net.bridge.bridge-nf-call-iptables = 1 
            net.bridge.bridge-nf-call-ip6tables = 1 
            net.ipv4.ip_forward = 1
    notify:
      - sysctl system

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      state: present
      filename: docker.list

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Set Systemd as Cgroups for Containerd
    ansible.builtin.blockinfile:
      path: "/etc/containerd/config.toml"
      block: | 
            [plugins."io.containerd.grpc.v1.cri"] 
                 systemd_cgroup = true
    notify:
      - containerd status

  - name: Add aws user user to docker group
    user:
      name: ubuntu
      # name: ec2-user
      group: docker